select = [
    "E", "W", # pycodestyle
    "F",  # pyflakes
    "D",  # pydocstyle
    "I",  # isort
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
]

line-length = 120

exclude = [
    "integration_test",
    "test_*",
    ".pytest_cache",
    ".eggs",
    ".egg_info",
    "build",
    "venv"
]

[pydocstyle]
convention = "google"