# This workflow runs unit tests and integration tests against the last three
# python versions on windows and ubuntu.


name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test:
    name: Unit Tests
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install -e . 
    
    - name: Run Unit Tests
      run: |
        coverage run --include=edk2toolext\* -m pytest --junitxml=test.junit.xml --html=pytest_report.html --self-contained-html
        coverage report

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: false
    
    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts-${{matrix.os}}-${{matrix.python-version}}
        path: |
          pytest_report.html
          test.junit.xml
      if: failure()
  
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    env:
      python-version: "3.11"
      node-version: "19"
      package-src: "edk2toolext"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      
      - name: Set up Node ${{ env.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version}}
      
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade -r docs/user/requirements.txt
          pip install -e .

      - name: Install npm dependencies
        run: |
          npm install -g markdownlint-cli@0.32.2
          npm install -g cspell@5.20.0
      
      - name: Run flake8
        run: flake8 ${{ env.package-src }}
      
      - name: Run markdownlint
        run: markdownlint "**/*.md"
      
      - name: Run cspell
        run: cspell -c .cspell.json "**/*.py" "**/*.md"
      
      - name: Run pydocstyle
        run: pydocstyle ${{ env.package-src }}
      
      - name: Run basic dev tests
        run: python BasicDevTests.py
  