# This workflow runs unit tests against the specified python versions on both
# ubuntu and windows. Additionally, it performs CI against the codebase.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  uses: Javagedes/edk2-pytool-extensions/.github/workflows/VariableProducer.yml@gh-action
  
  ci:
    needs: produce-variables
    uses: Javagedes/edk2-pytool-extensions/.github/workflows/CIRunner.yml@gh-action
    with:
      python-version: ${{ fromJson(needs.produce-variables.outputs.python-versions)[0] }}
      node-version: ${{ fromJson(needs.produce-variables.outputs.node-versions)[0] }}
      package-src: edk2toolext
  
  unit-test:
    needs: [produce-variables,ci]
    uses: Javagedes/edk2-pytool-extensions/.github/workflows/UnitTestRunner.yml@gh-action
    with:
      python-versions: ${{ needs.produce-variables.outputs.python-versions }}
  